In [7]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf, month_plot, quarter_plot
from statsmodels.tsa.holtwinters import ExponentialSmoothing, SimpleExpSmoothing
from statsmodels.tsa.seasonal import seasonal_decompose
from pmdarima import auto_arima, ARIMA, model_selection
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, mean_squared_error, mean_absolute_percentage_error

In [8]:
df= pd.read_csv(r"C:\Users\MINE\Desktop\bitcoin prediction\BTC_USD Bitfinex Historical Data (1).csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4058 entries, 0 to 4057
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      4058 non-null   object
 1   Price     4058 non-null   object
 2   Open      4058 non-null   object
 3   High      4058 non-null   object
 4   Low       4058 non-null   object
 5   Vol.      4048 non-null   object
 6   Change %  4058 non-null   object
dtypes: object(7)
memory usage: 222.1+ KB

In [10]:
df.head()

         Date     Price      Open      High       Low   Vol. Change %
0  02/11/2026  67,023.0  68,873.0  69,352.0  66,644.0  2.11K   -2.69%
1  02/10/2026  68,873.0  70,166.0  70,541.0  67,975.0  1.89K   -1.84%
2  02/09/2026  70,166.0  70,381.0  71,494.0  68,400.0  2.63K   -0.31%
3  02/08/2026  70,381.0  69,389.0  72,255.0  68,966.0  1.50K    1.43%
4  02/07/2026  69,389.0  70,639.0  71,668.0  67,465.0  1.96K   -1.76%

In [13]:
df.Date= pd.to_datetime(df.Date)

In [18]:
df.head(10)

              Price     Open     High      Low   Vol. Change %
Date
2026-02-11  67023.0  68873.0  69352.0  66644.0  2.11K   -2.69%
2026-02-10  68873.0  70166.0  70541.0  67975.0  1.89K   -1.84%
2026-02-09  70166.0  70381.0  71494.0  68400.0  2.63K   -0.31%
2026-02-08  70381.0  69389.0  72255.0  68966.0  1.50K    1.43%
2026-02-07  69389.0  70639.0  71668.0  67465.0  1.96K   -1.76%
2026-02-06  70634.0  62995.0  71800.0  60246.0  3.54K   12.22%
2026-02-05  62940.0  73280.0  73426.0  62590.0  4.25K  -14.11%
2026-02-04  73280.0  75892.0  77054.0  72149.0  3.00K   -3.44%
2026-02-03  75892.0  78848.0  79276.0  73104.0  2.49K   -3.75%
2026-02-02  78848.0  77030.0  79397.0  75090.0  4.28K    2.38%

In [15]:
df.set_index('Date', inplace=True)

In [16]:
col= ['Price', 'Open', 'High', 'Low']
for col in col:
  df[col]= df[col].str.replace(',','').astype('float64')

In [19]:
df= df.asfreq('D')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4060 entries, 2015-01-01 to 2026-02-11
Freq: D
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Price     4058 non-null   float64
 1   Open      4058 non-null   float64
 2   High      4058 non-null   float64
 3   Low       4058 non-null   float64
 4   Vol.      4048 non-null   object
 5   Change %  4058 non-null   object
dtypes: float64(4), object(2)
memory usage: 222.0+ KB